name: Send Birthday Emails

on:
  workflow_dispatch:
  schedule:
    # 5pm IST -> 11:30am UTC
    - cron: '30 11 * * *'
    # 11am IST -> 5:30am UTC
    - cron: '30 5 * * *'

jobs:
  trigger-email:
    runs-on: ubuntu-latest

    steps:
      - name: Call the API to send birthday emails
        run: |
          curl -X POST https://dob-app.onrender.com/api/send-birthday-emails
