name: Send Birthday Emails
on:
  workflow_dispatch:
  schedule:
    # 6:30pm IST -> 1:00pm UTC
    - cron: '0 13 * * *'
    # 11am IST -> 5:30am UTC
    - cron: '30 5 * * *'

jobs:
  trigger-email:
    runs-on: ubuntu-latest
    steps:
      - name: Show timestamp (for debug)
        run: date -u
      
      - name: Call the API to send birthday emails
        run: |
          curl -X POST https://dob-app.onrender.com/api/send-birthday-emails
